"""Consent text, versions, and the AI disclosure for sensitive-data features.

Bump the VERSION constant whenever the consent text changes materially — the skin
route requires the operator's (and customer's) active consent to match the CURRENT
version, so a material change forces re-consent. That is the defensible posture under
Washington's My Health My Data Act and Illinois BIPA.

See SECURITY-PRIVACY.md for the legal rationale.
"""
import hashlib

from fastapi import HTTPException
from sqlalchemy import select
from sqlalchemy.orm import Session

# Bump on any material change to the text below. Format: skin-vN-YYYY-MM.
SKIN_CONSENT_VERSION = "skin-v1-2026-06"

# The consultant accepts responsibility for collecting customer consent and for how
# derived skin data is used. Gates the whole skin-analysis feature (one-time).
OPERATOR_CONSENT_TEXT = (
    "I understand that the skin analysis feature processes a customer's photo to derive "
    "cosmetic skin attributes (such as undertone and Fitzpatrick skin type). I confirm "
    "that before running an analysis I will obtain each customer's explicit consent, that "
    "I will use this information only to recommend cosmetic products, and that I will not "
    "represent any output as medical advice or a diagnosis. I understand the customer can "
    "ask me to delete their skin data at any time and that I can do so from this app."
)

# Shown to (or read to) the customer before their photo is analyzed. The consultant
# records that the customer agreed.
CUSTOMER_CONSENT_TEXT = (
    "I consent to having a photo of my face analyzed to estimate cosmetic skin attributes "
    "(such as undertone and skin type) for the purpose of product recommendations. I "
    "understand this is not a medical assessment, that the photo is processed and not "
    "stored, and that I may request deletion of my skin information at any time."
)

# Persistent, non-dismissable disclosure shown on every generated skin observation.
# Satisfies the MHMDA disclosure expectation and the FTC/California SB 243 AI-disclosure push.
AI_DISCLOSURE = (
    "AI-generated cosmetic estimate — not medical advice or a diagnosis. "
    "Generated by an automated system from a photo you consented to share."
)


def text_sha256(text: str) -> str:
    """Integrity hash of the exact consent text shown, stored with each consent record."""
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


# Pre-computed hashes of the current-version texts (what a fresh grant must match).
OPERATOR_TEXT_SHA256 = text_sha256(OPERATOR_CONSENT_TEXT)
CUSTOMER_TEXT_SHA256 = text_sha256(CUSTOMER_CONSENT_TEXT)


def active_operator_consent(db: Session, user_id: str):
    """Latest non-revoked operator consent at the CURRENT version, or None."""
    from .models import ConsentRecord
    return db.scalar(
        select(ConsentRecord)
        .where(ConsentRecord.user_id == user_id,
               ConsentRecord.subject == "operator",
               ConsentRecord.scope == "skin",
               ConsentRecord.consent_version == SKIN_CONSENT_VERSION,
               ConsentRecord.revoked_at.is_(None))
        .order_by(ConsentRecord.granted_at.desc())
    )


def active_customer_consent(db: Session, user_id: str, customer_id: str):
    """Latest non-revoked customer consent at the CURRENT version, or None."""
    from .models import ConsentRecord
    return db.scalar(
        select(ConsentRecord)
        .where(ConsentRecord.user_id == user_id,
               ConsentRecord.subject == "customer",
               ConsentRecord.customer_id == customer_id,
               ConsentRecord.scope == "skin",
               ConsentRecord.consent_version == SKIN_CONSENT_VERSION,
               ConsentRecord.revoked_at.is_(None))
        .order_by(ConsentRecord.granted_at.desc())
    )


def require_skin_consent(db: Session, user, customer_id: str | None) -> None:
    """Gate the skin-analysis feature. Raises 403 with a machine-readable code if the
    operator (and, when a customer is named, that customer) has not given current consent.
    """
    if not active_operator_consent(db, user.id):
        raise HTTPException(403, {
            "code": "operator_consent_required",
            "message": "Accept the skin-analysis data terms before running an analysis.",
            "consent_version": SKIN_CONSENT_VERSION,
        })
    if customer_id and not active_customer_consent(db, user.id, customer_id):
        raise HTTPException(403, {
            "code": "customer_consent_required",
            "message": "Record this customer's consent before analyzing their photo.",
            "consent_version": SKIN_CONSENT_VERSION,
        })
